// nontest
IO.print(Bool)
IO.print(Class)
IO.print(Fiber)
IO.print(Fn)
IO.print(List)
IO.print(Map)
IO.print(MapKeySequence)
IO.print(MapValueSequence)
IO.print(Null)
IO.print(Num)
IO.print(Object)
IO.print(Range)
IO.print(Sequence)
IO.print(String)
