new Fn {
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  // 100
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  // 200
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  // 300
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  // 400
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  // 500
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  // 600
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  // 700
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  // 800
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  // 900
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  IO.print(1) // expect: 1
  IO.print(2) // expect: 2
  IO.print(3) // expect: 3
  IO.print(4) // expect: 4
  IO.print(5) // expect: 5
  IO.print(6) // expect: 6
  IO.print(7) // expect: 7
  IO.print(8) // expect: 8
  IO.print(9) // expect: 9
  IO.print(10) // expect: 10
  // 1000
}.call()

