fn {
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  // 100
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  // 200
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  // 300
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  // 400
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  // 500
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  // 600
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  // 700
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  // 800
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  // 900
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  IO.write(1) // expect: 1
  IO.write(2) // expect: 2
  IO.write(3) // expect: 3
  IO.write(4) // expect: 4
  IO.write(5) // expect: 5
  IO.write(6) // expect: 6
  IO.write(7) // expect: 7
  IO.write(8) // expect: 8
  IO.write(9) // expect: 9
  IO.write(10) // expect: 10
  // 1000
}.call

