Fn.new {
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  // 100
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  // 200
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  // 300
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  // 400
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  // 500
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  // 600
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  // 700
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  // 800
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  // 900
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  System.print(1) // expect: 1
  System.print(2) // expect: 2
  System.print(3) // expect: 3
  System.print(4) // expect: 4
  System.print(5) // expect: 5
  System.print(6) // expect: 6
  System.print(7) // expect: 7
  System.print(8) // expect: 8
  System.print(9) // expect: 9
  System.print(10) // expect: 10
  // 1000
}.call()

